
from tkinter import *
from tkinter.ttk import Progressbar
from tkinter.ttk import Combobox
from tkinter.ttk import Notebook
from tkinter.ttk import Treeview
from PIL import Image, ImageTk
import tkinter.font
import tkinter.messagebox
import customtkinter
customtkinter.set_appearance_mode("Dark")
customtkinter.set_default_color_theme("dark-blue")



class DBET_GUI():
    def __init__(self, parent):
        self.gui(parent)

    def gui(self, parent):
        if parent == 0:
            self.w1 = Tk()
            self.w1.configure(bg = '#414141')
            self.w1.geometry('1440x950')
        else:
            self.w1 = Frame(parent)
            self.w1.configure(bg = '#414141')
            self.w1.place(x = 0, y = -3, width = 1440, height = 950)
        self.buttonUserAdd = customtkinter.CTkButton(self.w1, text = "Add Record", fg_color = "#3e3e3e", font = ("Calibri", 14), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonUserAdd.place(x = 20, y = 760)
        self.buttonUserUpdate = customtkinter.CTkButton(self.w1, text = "Update Record", fg_color = "#3e3e3e", font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonUserUpdate.place(x = 150, y = 760)
        self.buttonUserCommit = customtkinter.CTkButton(self.w1, text = "Commit Changes", fg_color = "#3e3e3e", font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonUserCommit.place(x = 280, y = 760)
        self.labelUser = customtkinter.CTkLabel(self.w1, text = "User Table", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 400, height = 22)
        self.labelUser.place(x = 10, y = 50)
        self.labelPlace = customtkinter.CTkLabel(self.w1, text = "Place's Table", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 400, height = 22)
        self.labelPlace.place(x = 420, y = 10)
        self.labelReview = customtkinter.CTkLabel(self.w1, text = "Reviews Table", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 400, height = 22)
        self.labelReview.place(x = 930, y = 10)
        self.labelTitle = customtkinter.CTkLabel(self.w1, text = "Database Editorial Tool", anchor='w', font = ("Calibri", 24), cursor = "arrow", state = "normal", width = 400, height = 42)
        self.labelTitle.place(x = 10, y = 10)
        self.tbUsername = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 280, height = 22)
        self.tbUsername.place(x = 130, y = 540)
        self.userTableLabel1 = customtkinter.CTkLabel(self.w1, text = "Username\n", anchor='w', font = ("Calibri", 12), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.userTableLabel1.place(x = 10, y = 540)
        self.tbName = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 280, height = 22)
        self.tbName.place(x = 130, y = 600)
        self.tbAge = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 280, height = 22)
        self.tbAge.place(x = 130, y = 630)
        self.tbJob = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 280, height = 22)
        self.tbJob.place(x = 130, y = 660)
        self.userTableLabel2 = customtkinter.CTkLabel(self.w1, text = "Password", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.userTableLabel2.place(x = 10, y = 570)
        self.userTableLabel3 = customtkinter.CTkLabel(self.w1, text = "Name", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.userTableLabel3.place(x = 10, y = 600)
        self.userTableLabel4 = customtkinter.CTkLabel(self.w1, text = "Age", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.userTableLabel4.place(x = 10, y = 630)
        self.userTableLabel5 = customtkinter.CTkLabel(self.w1, text = "Job", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.userTableLabel5.place(x = 10, y = 660)
        self.tbPlaceID = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbPlaceID.place(x = 540, y = 540)
        self.labelPlace1 = customtkinter.CTkLabel(self.w1, text = "ID", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelPlace1.place(x = 420, y = 540)
        self.tbPlaceName = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbPlaceName.place(x = 540, y = 570)
        self.tbOpenHours = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbOpenHours.place(x = 540, y = 600)
        self.tbAddress = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbAddress.place(x = 540, y = 630)
        self.tbPhone = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbPhone.place(x = 540, y = 660)
        self.labelPlace2 = customtkinter.CTkLabel(self.w1, text = "Name", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelPlace2.place(x = 420, y = 570)
        self.labelPlace3 = customtkinter.CTkLabel(self.w1, text = "Open Hours", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelPlace3.place(x = 420, y = 600)
        self.labelPlace4 = customtkinter.CTkLabel(self.w1, text = "Address", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelPlace4.place(x = 420, y = 630)
        self.labelPlace5 = customtkinter.CTkLabel(self.w1, text = "Phone No.", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelPlace5.place(x = 420, y = 660)
        self.tbPassword = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 280, height = 22)
        self.tbPassword.place(x = 130, y = 570)
        self.tbPrice = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbPrice.place(x = 540, y = 690)
        self.labelPlace6 = customtkinter.CTkLabel(self.w1, text = "Price", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelPlace6.place(x = 420, y = 690)
        self.tbRating = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbRating.place(x = 1050, y = 600)
        self.labelReview1 = customtkinter.CTkLabel(self.w1, text = "Rating", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelReview1.place(x = 930, y = 600)
        self.tbReviewName = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbReviewName.place(x = 1050, y = 630)
        self.tbMainText = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbMainText.place(x = 1050, y = 660)
        self.tbCategory = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbCategory.place(x = 1050, y = 690)
        self.Date = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.Date.place(x = 1050, y = 720)
        self.labelReview2 = customtkinter.CTkLabel(self.w1, text = "Name", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelReview2.place(x = 930, y = 630)
        self.labelReview3 = customtkinter.CTkLabel(self.w1, text = "Main Text", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelReview3.place(x = 930, y = 660)
        self.labelReview4 = customtkinter.CTkLabel(self.w1, text = "Category", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelReview4.place(x = 930, y = 690)
        self.labelReview5 = customtkinter.CTkLabel(self.w1, text = "Date", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelReview5.place(x = 930, y = 720)
        self.userTable = Treeview(self.w1, selectmode = 'browse', show = 'tree')
        self.userTable.place(x = 10, y = 70, width = 400, height = 460)
        self.placeTable = Treeview(self.w1, selectmode = 'browse', show = 'tree')
        self.placeTable.place(x = 420, y = 30, width = 500, height = 500)
        self.reviewTable = Treeview(self.w1, selectmode = 'browse', show = 'tree')
        self.reviewTable.place(x = 930, y = 30, width = 500, height = 500)
        self.tbReviewUsername = customtkinter.CTkEntry(self.w1, font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbReviewUsername.place(x = 1050, y = 540)
        self.lalbelReview6 = customtkinter.CTkLabel(self.w1, text = "Username", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.lalbelReview6.place(x = 930, y = 540)
        self.tbReviewPlaceID = customtkinter.CTkEntry(self.w1, fg_color = "#3e3e3e", font = ("Calibri", 9), state = "normal", width = 380, height = 22)
        self.tbReviewPlaceID.place(x = 1050, y = 570)
        self.labelReview7 = customtkinter.CTkLabel(self.w1, text = "Place ID", anchor='w', font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 90, height = 22)
        self.labelReview7.place(x = 930, y = 570)
        self.buttonPlaceAdd = customtkinter.CTkButton(self.w1, text = "Add Record", fg_color = "#3e3e3e", font = ("Calibri", 14), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonPlaceAdd.place(x = 470, y = 760)
        self.buttonPlaceUpdate = customtkinter.CTkButton(self.w1, text = "Update Record", fg_color = "#3e3e3e", font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonPlaceUpdate.place(x = 600, y = 760)
        self.buttonPlaceCommit = customtkinter.CTkButton(self.w1, text = "Commit Changes", fg_color = "#3e3e3e", font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonPlaceCommit.place(x = 730, y = 760)
        self.buttonReviewAdd = customtkinter.CTkButton(self.w1, text = "Add Record", fg_color = "#3e3e3e", font = ("Calibri", 14), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonReviewAdd.place(x = 1000, y = 760)
        self.buttonReviewUpdate = customtkinter.CTkButton(self.w1, text = "Update Record", fg_color = "#3e3e3e", font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonReviewUpdate.place(x = 1130, y = 760)
        self.buttonReviewCommit = customtkinter.CTkButton(self.w1, text = "Commit Changes", fg_color = "#3e3e3e", font = ("Calibri", 9), cursor = "arrow", state = "normal", width = 120, height = 42)
        self.buttonReviewCommit.place(x = 1260, y = 760)

if __name__ == '__main__':
    a = DBET_GUI(0)
    a.w1.mainloop()
